# Generated by Django 5.2.7 on 2025-11-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_profile_avatar_alter_answer_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="media/avatars/gray.png", null=True, upload_to="avatars/"
            ),
        ),
    ]
