# Generated by Django 5.2.7 on 2025-11-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="gray.png", null=True, upload_to="avatars/"
            ),
        ),
    ]
