# Generated by Django 5.2.7 on 2025-12-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_questionlike_value_alter_answer_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="like_amount",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
