# Generated by Django 5.2.7 on 2025-12-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_question_like_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerlike",
            name="value",
            field=models.SmallIntegerField(
                choices=[(1, "Like"), (-1, "Dislike")], default=1
            ),
            preserve_default=False,
        ),
    ]
