# Generated by Django 5.2.7 on 2025-12-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_answerlike_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
    ]
