# Generated by Django 5.2.7 on 2025-12-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_answer_is_correct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="like_amount",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
