# Generated by Django 5.2.7 on 2025-12-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_answer_like_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
